services:
  postgres:
    image: postgres:14.4-alpine
    container_name: learning-postgres
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_USER:  "student"
      POSTGRES_DB:  "learning"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nats1:
    image: nats:2.8-alpine
    container_name: learning-nats1
    command: -js -sd /data
    volumes:
      - nats1:/data
    ports:
      - 4222:4222

volumes:
  postgres:
  nats1: